### ISSUE TITLE
Reset CSS

### ISSUE THREAD

**Issue by seejamescode** [IBM/type-checker#14]
As a user, I do not want to see styling from the page I am on affect the type checker display:
<img width="258" alt="screen shot 2017-10-17 at 1 10 37 pm" src="https://user-images.githubusercontent.com/7519029/31681357-a647537c-b33c-11e7-9717-ffd569aa58b6.png">

**Comment by diego-codes** [comment]
I'm closing this issue because we're going in a new direction with developer tools which does not involve adding stuff to the DOM.
