### ISSUE TITLE
Opening and closing devtools

### ISSUE THREAD

**Issue by seejamescode** [IBM/type-checker#15]
When a user opens Chrome devtools and then closes it again, the IBM Type Checker UI positions itself to the bottom of the screen:
<img width="1433" alt="screen shot 2017-10-17 at 1 12 47 pm" src="https://user-images.githubusercontent.com/7519029/31681495-fc1a827e-b33c-11e7-9587-bd1779c0a837.png">

**Comment by diego-codes** [comment]
I'm closing this issue because we're going in a new direction with developer tools which does not involve adding stuff to the DOM.
