### ISSUE TITLE
CI: Travis

### ISSUE THREAD

**Issue by diego-codes** [IBM/type-checker#7]
Create Travis flow to continuously push changes on `master` to Google Chrome Store and Firefox Add-ons.

**Comment by diego-codes** [comment]
Opening back up because I forgot Firefox...

**Comment by diego-codes** [comment]
@seejamescode, we'll need to get together on this to update the Travis variables with the API keys to get this to work.

**Comment by seejamescode** [comment]
Just swing by my desk this afternoon! I’m free after 2pm

**Comment by diego-codes** [comment]
After much trial and error. We got it to work. 🤕

**Comment by seejamescode** [comment]
> After much trial and error. We got it to work. 

DevOps in a nutshell.
